name: elec_lib_app
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  bloc: any
  cupertino_icons: any
  equatable: any
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: any
  flutter_localization: any
  get_it: any
  shared_preferences: any
  flutter_svg: any
  flex_color_scheme: ^7.3.1
  flutter_rating_bar: ^4.0.1
  cloud_firestore: ^5.0.0
  firebase_core: any
  firebase_storage: ^12.0.0
  firebase_auth: ^5.0.0
  dartz: ^0.10.1
  flutter_easyloading: ^3.0.5


dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  assets:
    - assets/lang/ar.json
    - assets/lang/en.json
    - assets/images/splash/
    - assets/images/
    - assets/images/image_test/
    - assets/images/signup/
    - assets/images/login_or_register/
    - assets/images/login/
  fonts:
  - family: Cairo
    fonts:
    - asset: assets/fonts/cairo/Cairo.ttf

  - family: Rubik
    fonts:
    - asset: assets/fonts/rubik/Rubik.ttf
